# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.srcs/sources_1/ip/cmac_gty_full/cmac_gty_full.xci
# IP: The module: 'cmac_gty_full' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmac_gty_full'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmac_gty_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.srcs/sources_1/ip/cmac_gty_full/cmac_gty_full.xci
# IP: The module: 'cmac_gty_full' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmac_gty_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmac_gty_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
