#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jan 21 10:01:01 CST 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_trico_top_func_synth -key {Post-Synthesis:sim_1:Functional:tb_trico_top} -tclbatch tb_trico_top.tcl -protoinst "protoinst_files/bd_43c9.protoinst" -protoinst "protoinst_files/bd_fb99.protoinst" -protoinst "protoinst_files/cms.protoinst" -log simulate.log"
xsim tb_trico_top_func_synth -key {Post-Synthesis:sim_1:Functional:tb_trico_top} -tclbatch tb_trico_top.tcl -protoinst "protoinst_files/bd_43c9.protoinst" -protoinst "protoinst_files/bd_fb99.protoinst" -protoinst "protoinst_files/cms.protoinst" -log simulate.log

