# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.srcs/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/cms_cms_subsystem_0_0.xci
# IP: The module: 'cms_cms_subsystem_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/bd_fb99.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fb99 || ORIG_REF_NAME==bd_fb99} -quiet] -quiet

# IP: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_0/bd_fb99_shell_cmc_subsystem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fb99_shell_cmc_subsystem_0 || ORIG_REF_NAME==bd_fb99_shell_cmc_subsystem_0} -quiet] -quiet

# XDC: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/bd_fb99_ooc.xdc

# XDC: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/synth/cms_cms_subsystem_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cms_cms_subsystem_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.srcs/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/cms_cms_subsystem_0_0.xci
# IP: The module: 'cms_cms_subsystem_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/bd_fb99.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fb99 || ORIG_REF_NAME==bd_fb99} -quiet] -quiet

# IP: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_0/bd_fb99_shell_cmc_subsystem_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fb99_shell_cmc_subsystem_0 || ORIG_REF_NAME==bd_fb99_shell_cmc_subsystem_0} -quiet] -quiet

# XDC: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/bd_fb99_ooc.xdc

# XDC: /home/playmaker/Desktop/mkxue/corundum/fpga/mqnic/Alveo/fpga_100g/fpga_AU200/corundum-trico.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/synth/cms_cms_subsystem_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cms_cms_subsystem_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
